### ISSUE TITLE
I can still see the difficulty when I am solving a problem. Attaching the screenshot.

### ISSUE THREAD

**Issue by aditya30394** [Nevvea7/eyepatch#3]
![image](https://user-images.githubusercontent.com/8336542/47680865-104f2600-db96-11e8-8c0a-3ac87daee9f8.png)

**Comment by theGreatHeisenberg** [comment]
Hi Aditya, 

You can use [this](https://chrome.google.com/webstore/detail/leetcode-mask/nmgainefgbnakmdojhcnmceaogankngk) extension which supports Leetcode's new design. 

I have forked this repository [here](https://github.com/theGreatHeisenberg/eyepatch/) and made some changes.

**Comment by anna-yn** [comment]
closing this since @theGreatHeisenberg has kindly fixed the issue
